<?php

namespace MennenOnline\Shopware5ApiConnector\Endpoints;

use MennenOnline\Shopware5ApiConnector\Enums\EndpointEnum;
use MennenOnline\Shopware5ApiConnector\Shopware5ApiConnector;

final class AddressEndpoint extends Endpoint
{
    protected EndpointEnum|null $endpoint = EndpointEnum::ADDRESSES;

    public function initialize(?string $url = null, ?string $username = null, ?string $password = null): Shopware5ApiConnector
    {
        $this->endpoint = EndpointEnum::ADDRESSES;

        return parent::initialize($url, $username, $password); // TODO: Change the autogenerated stub
    }
}
