<?php

namespace MennenOnline\Shopware5ApiConnector\Endpoints;

use MennenOnline\Shopware5ApiConnector\Enums\EndpointEnum;
use MennenOnline\Shopware5ApiConnector\Models\BaseResponseModel;
use MennenOnline\Shopware5ApiConnector\Models\Endpoints\CustomerGroup\CustomerGroupListModel;
use MennenOnline\Shopware5ApiConnector\Models\Endpoints\CustomerGroup\CustomerGroupSingleModel;
use MennenOnline\Shopware5ApiConnector\Shopware5ApiConnector;

class CustomerGroupEndpoint extends Endpoint
{
    public function initialize(?string $url = null, ?string $username = null, ?string $password = null): Shopware5ApiConnector
    {
        $this->endpoint = EndpointEnum::CUSTOMER_GROUPS;

        return parent::initialize($url, $username, $password); // TODO: Change the autogenerated stub
    }

    public function getAll(?int $limit = null): BaseResponseModel {
        $this->responseModel = CustomerGroupListModel::class;

        return parent::getAll($limit);
    }

    public function getSingle(int|string $id): BaseResponseModel {
        $this->responseModel = CustomerGroupSingleModel::class;

        return parent::getSingle($id);
    }
}
