<?php

namespace MennenOnline\Shopware5ApiConnector\Endpoints;

use MennenOnline\Shopware5ApiConnector\Enums\EndpointEnum;
use MennenOnline\Shopware5ApiConnector\Models\BaseResponseModel;
use MennenOnline\Shopware5ApiConnector\Models\Endpoints\Customer\CustomerListModel;
use MennenOnline\Shopware5ApiConnector\Models\Endpoints\Customer\CustomerSingleModel;
use MennenOnline\Shopware5ApiConnector\Shopware5ApiConnector;

class CustomerEndpoint extends Endpoint
{
    public function initialize(?string $url = null, ?string $username = null, ?string $password = null): Shopware5ApiConnector
    {
        $this->endpoint = EndpointEnum::CUSTOMERS;

        return parent::initialize($url, $username, $password); // TODO: Change the autogenerated stub
    }

    public function getAll(?int $limit = null): BaseResponseModel {
        $this->responseModel = CustomerListModel::class;

        return parent::getAll($limit);
    }

    public function getSingle(int|string $id): BaseResponseModel {
        $this->responseModel = CustomerSingleModel::class;

        return parent::getSingle($id);
    }
}
